### ISSUE TITLE
bot.say() Issue?

### ISSUE THREAD

**Issue by Jessey-DeVaney** [jakeryang/youversion-votd-discord#2]
Logged in as: VOTD Bot
Ignoring exception in command votd:
Traceback (most recent call last):
 File “/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py”, line 85, in wrapped
  ret = await coro(*args, **kwargs)
 File “./main.py”, line 106, in votd
  await bot.say(embed=embed)
AttributeError: ‘Bot’ object has no attribute ‘say’

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File “/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py”, line 903, in invoke
  await ctx.command.invoke(ctx)
 File “/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py”, line 855, in invoke
  await injected(*ctx.args, **ctx.kwargs)
 File “/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py”, line 94, in wrapped
  raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: ‘Bot’ object has no attribute ‘say’

**Comment by jakegut** [comment]
Looks like the discord.py version you already have installed is newer than the version this is built with. I should be able to fix this just by updating the code.

**Comment by Jessey-DeVaney** [comment]
My other bots are using Discord.py version 1.0.0 just for reference. There may be a newer version past that though.

**Comment by jakegut** [comment]
Ok, I'll update it to that exact version then.

**Comment by jakegut** [comment]
@Jessey-DeVaney Luckily I found my YV API token so I was able to test it and it works for me. Let me know if it works for you.

**Comment by Jessey-DeVaney** [comment]
@jakegut Did you update the discord.py code references or no since it worked with yours?

**Comment by jakegut** [comment]
Yes I updated the references, it should work with discord.py v1.0.0

**Comment by Jessey-DeVaney** [comment]
Using your updated version I was able to get the bot to work and respond. Funny thing though, the same YV token I have that according to my curl request isn't valid, works for the Discord Bot? Kinda weird. Not sure what that means.

**Comment by jakegut** [comment]
If you're not having any more issues I'll go ahead and close this issue.
